apiVersion: v1
kind: PersistentVolume
metadata:
  name: sspl-pv-sda
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: sspl-pvc-sda
  local:
    path: /dev/sda
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - dell09-m01.colo.seagate.com