apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sspl-pvc-sda
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 10Mi
  volumeName: sspl-pv-sda